spring.application.name=ShopFlow
server.port=8082

#32 caracters MIN
#if user tries to cahange the ROLE -> will no longer match
application.security.jwt.secret-key = WHATEVERISWRONGWITHTHISSOFTW_32!
	

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#Connexion a DB

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:shopflowdb;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=


#afficher sql dans le console !!!
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true



spring.datasource.continue-on-error=true